SET CURRENT SCHEMA = CURRENT USER;

DROP TABLE <SCHEMA>.LOCALUSER1;
DROP TABLE <SCHEMA>.LOCALUSER2;
DROP TABLE <SCHEMA>.LOCALUSER3;

  CREATE TABLE <SCHEMA>.<SCHEMA>."LOCALUSER1"
   (    "ID" VARCHAR(20) NOT NULL,
        "USERNAME" VARCHAR(250)
   );

  CREATE TABLE <SCHEMA>.<SCHEMA>."LOCALUSER2"
   (    "ID" VARCHAR(20) NOT NULL,
        "USERNAME" VARCHAR(250)
   );

  CREATE TABLE <SCHEMA>."LOCALUSER3"
   (    "ID" VARCHAR(20) NOT NULL,
        "USERNAME" VARCHAR(250)
   );

  CREATE TABLE <SCHEMA>."MyModel"
   (
        "id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
        "Make" VARCHAR(25),
        "Model" VARCHAR(25),
        "Year" SMALLINT,
        "Color" VARCHAR(25)
   );

-- SET CURRENT SCHEMA = STRONGLOOP;

--------------------------------------------------------
--  File created - Thursday-September-05-2013
--------------------------------------------------------
DROP TABLE LOCALUSER;
DROP TABLE CUSTOMER;
DROP TABLE SESSION;
DROP TABLE LOCATION;
DROP TABLE PRODUCT;
DROP TABLE INVENTORY;
DROP TABLE RESERVATION;

-- SET CURRENT SCHEMA = STRONGLOOP;

--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE <SCHEMA>."CUSTOMER"
   (	"ID" VARCHAR(20) NOT NULL,
	"USERNAME" VARCHAR(1024),
	"EMAIL" VARCHAR(1024),
	"PASSWORD" VARCHAR(1024),
	"NAME" VARCHAR(40),
	"MILITARY_AGENCY" VARCHAR(20),
	"REALM" VARCHAR(1024),
	"EMAILVERIFIED" CHAR(1),
	"VERIFICATIONTOKEN" VARCHAR(1024),
	"CREDENTIALS" VARCHAR(1024),
	"CHALLENGES" VARCHAR(1024),
	"STATUS" VARCHAR(1024),
	"CREATED" DATE,
	"LASTUPDATED" DATE
   );

--------------------------------------------------------
--  DDL for Table INVENTORY
--------------------------------------------------------

  CREATE TABLE <SCHEMA>."INVENTORY"
   (	"ID" VARCHAR(20) NOT NULL,
	"PRODUCT_ID" VARCHAR(20) NOT NULL,
	"LOCATION_ID" VARCHAR(20),
	"AVAILABLE" INTEGER,
	"TOTAL" INTEGER
   );


-- CREATE SEQUENCE INVENTORY_ID_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;
-- CREATE OR REPLACE TRIGGER INVENTORY_ID_TRIGGER BEFORE
--  INSERT ON INVENTORY FOR EACH row BEGIN
--  SELECT INVENTORY_ID_SEQ.nextval INTO :new.id FROM dual;
-- END;
-- 
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE <SCHEMA>."LOCATION"
   (	"ID" VARCHAR(20) NOT NULL,
	"STREET" VARCHAR(64),
	"CITY" VARCHAR(64),
	"ZIPCODE" VARCHAR(16),
	"NAME" VARCHAR(32),
	"GEO" VARCHAR(1024)
   );

--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE <SCHEMA>."PRODUCT"
   (	"ID" VARCHAR(20) NOT NULL,
	"NAME" VARCHAR(64),
	"AUDIBLE_RANGE" INTEGER,
	"EFFECTIVE_RANGE" INTEGER,
	"ROUNDS" INTEGER,
	"EXTRAS" VARCHAR(64),
	"FIRE_MODES" VARCHAR(64)
   );

--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE <SCHEMA>."RESERVATION"
   (	"ID" VARCHAR(20) NOT NULL,
	"PRODUCT_ID" VARCHAR(20),
	"LOCATION_ID" VARCHAR(20),
	"CUSTOMER_ID" VARCHAR(20),
	"QTY" INT,
	"STATUS" VARCHAR(20),
	"RESERVE_DATE" DATE,
	"PICKUP_DATE" DATE,
	"RETURN_DATE" DATE
   );

--------------------------------------------------------
--  DDL for Table SESSION
--------------------------------------------------------

  CREATE TABLE <SCHEMA>."SESSION"
   (	"ID" VARCHAR(64) NOT NULL,
	"UID" VARCHAR(1024),
	"TTL" INT
   );

-- REM INSERTING into CUSTOMER
-- SET DEFINE OFF;
INSERT INTO <SCHEMA>.CUSTOMER (ID,USERNAME,EMAIL,PASSWORD,NAME,MILITARY_AGENCY,REALM,EMAILVERIFIED,VERIFICATIONTOKEN,CREDENTIALS,CHALLENGES,STATUS,CREATED,LASTUPDATED) VALUES ('612','bat','bat@bar.com','$2a$10$BEG18wcYQn7TRkFIc59EB.vmnsEwqJWMlYM4DNG73iZb.MKA1rjAC',null,null,null,null,null,'[]','[]',null,null,null) WITH NC;
INSERT INTO <SCHEMA>.CUSTOMER (ID,USERNAME,EMAIL,PASSWORD,NAME,MILITARY_AGENCY,REALM,EMAILVERIFIED,VERIFICATIONTOKEN,CREDENTIALS,CHALLENGES,STATUS,CREATED,LASTUPDATED) VALUES ('613','baz','baz@bar.com','$2a$10$jkSYF2gLMdI4CwVQh8AStOs0b24lDu9p8jccnmri/0rvhtwsicm9C',null,null,null,null,null,'[]','[]',null,null,null) WITH NC;
INSERT INTO <SCHEMA>.CUSTOMER (ID,USERNAME,EMAIL,PASSWORD,NAME,MILITARY_AGENCY,REALM,EMAILVERIFIED,VERIFICATIONTOKEN,CREDENTIALS,CHALLENGES,STATUS,CREATED,LASTUPDATED) VALUES ('610','foo','foo@bar.com','$2a$10$tn1hN7Xv6x74cCB7tVfwkeaaJTd4/6q4RbCMzgmAJeWe40xqrRSui',null,null,null,null,null,'[]','[]',null,null,null) WITH NC;
INSERT INTO <SCHEMA>.CUSTOMER (ID,USERNAME,EMAIL,PASSWORD,NAME,MILITARY_AGENCY,REALM,EMAILVERIFIED,VERIFICATIONTOKEN,CREDENTIALS,CHALLENGES,STATUS,CREATED,LASTUPDATED) VALUES ('611','bar','bar@bar.com','$2a$10$a8mCol6d5vQXm6vubqXl8e5V66StEg6E8vzjQqPpoyk95Vm3smpiK',null,null,null,null,null,'[]','[]',null,null,null) WITH NC;
-- REM INSERTING into INVENTORY
-- SET DEFINE OFF;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('441','6','91',8,19) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('442','7','91',21,23) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('443','8','91',35,63) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('444','9','91',0,7) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('445','10','91',0,2) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('446','11','91',1,6) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('447','12','91',67,77) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('448','13','91',7,51) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('449','14','91',39,96) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('450','15','91',36,74) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('451','16','91',15,73) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('453','18','91',0,19) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('452','17','91',36,63) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('454','19','91',24,94) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('455','20','91',8,38) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('456','21','91',41,58) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('457','22','91',18,22) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('458','23','91',25,37) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('459','24','91',39,60) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('460','25','91',30,55) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('461','26','91',4,4) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('462','27','91',6,17) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('463','28','91',63,82) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('464','29','91',30,76) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('465','30','91',13,31) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('466','31','91',10,59) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('467','32','91',39,80) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('468','33','91',69,89) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('469','34','91',62,93) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('470','35','91',13,27) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('471','36','91',8,22) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('472','37','91',0,31) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('473','38','91',9,79) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('474','39','91',6,49) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('475','40','91',39,40) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('476','41','91',1,22) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('477','42','91',12,82) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('478','43','91',1,7) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('479','44','91',15,26) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('480','45','91',22,31) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('481','46','91',64,65) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('482','47','91',10,99) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('483','48','91',26,56) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('484','49','91',14,19) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('485','50','91',51,55) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('486','51','91',25,29) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('487','52','91',31,37) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('488','53','91',35,71) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('489','54','91',5,61) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('490','55','91',4,26) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('491','56','91',29,50) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('492','57','91',15,34) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('493','58','91',30,38) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('494','59','91',54,71) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('495','60','91',6,43) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('496','61','91',40,80) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('497','62','91',32,33) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('498','63','91',44,53) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('499','64','91',10,68) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('500','65','91',11,13) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('501','66','91',7,40) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('502','67','91',5,20) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('503','68','91',30,40) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('504','69','91',6,48) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('505','70','91',7,53) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('506','71','91',2,21) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('507','72','91',25,56) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('508','73','91',13,85) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('509','74','91',63,67) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('510','75','91',9,11) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('511','76','91',18,46) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('512','77','91',7,88) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('513','78','91',36,55) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('514','79','91',8,33) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('515','80','91',63,73) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('517','82','91',2,5) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('516','81','91',36,71) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('518','83','91',11,11) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('519','84','91',21,39) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('520','85','91',90,91) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('521','86','91',1,2) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('522','87','91',36,47) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('523','2','92',6,7) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('524','3','92',15,23) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('525','4','92',1,1) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('527','6','92',22,24) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('526','5','92',37,42) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('528','7','92',12,13) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('529','8','92',4,25) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('531','10','92',9,31) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('530','9','92',32,87) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('532','11','92',2,38) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('533','12','92',66,88) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('534','13','92',4,15) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('535','14','92',9,88) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('536','15','92',18,72) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('537','16','92',13,26) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('538','17','92',20,55) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('539','18','92',17,76) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('540','19','92',28,58) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('542','21','92',7,12) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('541','20','92',78,99) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('543','22','92',4,13) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('544','23','92',12,96) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('545','24','92',82,84) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('546','25','92',29,64) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('547','26','92',5,7) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('548','27','92',3,35) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('549','28','92',23,46) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('550','29','92',21,39) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('551','30','92',19,21) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('552','31','92',24,73) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('553','32','92',51,89) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('554','33','92',22,32) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('555','34','92',56,95) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('556','35','92',47,95) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('557','36','92',17,24) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('558','37','92',0,0) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('559','38','92',14,53) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('560','39','92',65,67) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('561','40','92',64,95) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('562','41','92',5,5) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('563','42','92',7,10) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('564','43','92',34,45) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('565','44','92',0,3) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('566','45','92',20,67) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('567','46','92',58,92) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('568','47','92',21,70) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('569','48','92',56,62) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('570','49','92',0,5) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('571','50','92',16,97) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('572','51','92',6,46) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('573','52','92',58,84) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('574','53','92',25,42) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('575','54','92',13,40) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('576','55','92',18,34) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('577','56','92',44,92) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('578','57','92',0,19) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('579','58','92',13,67) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('580','59','92',18,38) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('581','60','92',7,7) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('582','61','92',6,53) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('583','62','92',4,25) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('584','63','92',31,59) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('585','64','92',25,40) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('586','65','92',2,81) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('587','66','92',23,81) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('588','67','92',9,33) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('589','68','92',2,37) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('590','69','92',53,64) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('591','70','92',21,22) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('592','71','92',7,45) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('593','72','92',9,25) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('594','73','92',0,40) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('595','74','92',21,34) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('596','75','92',33,87) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('597','76','92',44,48) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('598','77','92',64,69) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('599','78','92',31,56) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('600','79','92',11,12) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('601','80','92',3,7) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('602','81','92',26,74) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('603','82','92',29,46) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('604','83','92',1,5) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('605','84','92',35,37) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('606','85','92',12,100) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('607','86','92',9,18) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('608','87','92',49,64) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('95','4','87',18,30) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('97','6','87',10,21) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('96','5','87',3,38) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('98','7','87',43,58) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('99','8','87',6,12) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('100','9','87',0,3) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('101','10','87',0,31) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('102','11','87',73,93) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('103','12','87',22,25) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('104','13','87',44,70) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('105','14','87',26,50) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('106','15','87',36,83) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('107','16','87',20,59) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('108','17','87',28,44) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('109','18','87',5,50) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('110','19','87',2,29) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('111','20','87',38,54) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('112','21','87',4,29) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('113','22','87',1,59) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('114','23','87',20,36) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('115','24','87',10,10) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('116','25','87',58,60) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('117','26','87',0,18) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('118','27','87',29,50) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('119','28','87',24,34) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('120','29','87',36,43) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('121','30','87',43,64) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('122','31','87',79,90) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('123','32','87',13,13) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('124','33','87',9,60) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('125','34','87',7,13) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('126','35','87',43,54) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('127','36','87',67,69) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('128','37','87',1,15) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('129','38','87',36,44) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('130','39','87',1,17) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('131','40','87',13,16) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('132','41','87',24,64) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('133','42','87',87,99) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('134','43','87',27,99) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('135','44','87',71,71) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('136','45','87',9,20) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('137','46','87',9,67) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('138','47','87',19,21) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('139','48','87',5,5) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('140','49','87',82,91) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('141','50','87',27,42) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('142','51','87',51,60) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('143','52','87',8,72) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('145','54','87',3,71) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('144','53','87',5,13) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('146','55','87',55,56) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('147','56','87',9,90) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('148','57','87',3,18) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('149','58','87',2,14) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('150','59','87',54,95) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('151','60','87',62,70) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('152','61','87',18,50) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('153','62','87',60,78) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('154','63','87',23,59) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('155','64','87',14,23) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('156','65','87',2,97) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('157','66','87',49,50) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('158','67','87',47,93) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('159','68','87',34,42) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('160','69','87',3,18) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('161','70','87',37,84) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('162','71','87',22,40) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('163','72','87',8,61) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('164','73','87',2,3) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('165','74','87',10,16) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('166','75','87',53,89) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('167','76','87',35,60) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('168','77','87',57,80) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('169','78','87',53,81) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('170','79','87',32,54) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('171','80','87',1,4) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('172','81','87',78,86) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('173','82','87',11,21) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('174','83','87',28,81) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('175','84','87',2,57) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('176','85','87',30,37) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('177','86','87',17,80) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('179','2','88',10,10) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('178','87','87',1,9) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('180','3','88',1,1) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('181','4','88',8,27) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('182','5','88',3,38) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('183','6','88',28,76) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('184','7','88',40,83) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('185','8','88',1,4) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('186','9','88',87,95) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('187','10','88',29,35) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('188','11','88',10,69) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('189','12','88',32,86) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('190','13','88',27,28) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('191','14','88',59,66) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('192','15','88',59,70) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('193','16','88',43,70) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('194','17','88',50,63) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('195','18','88',8,20) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('196','19','88',20,29) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('197','20','88',36,50) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('198','21','88',40,63) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('199','22','88',4,96) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('200','23','88',70,98) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('201','24','88',1,1) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('202','25','88',17,45) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('203','26','88',52,97) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('204','27','88',0,0) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('205','28','88',97,98) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('206','29','88',26,80) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('207','30','88',11,33) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('208','31','88',10,21) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('209','32','88',14,36) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('210','33','88',71,86) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('211','34','88',85,100) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('212','35','88',3,45) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('213','36','88',0,3) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('214','37','88',17,71) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('215','38','88',41,75) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('216','39','88',37,41) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('217','40','88',37,49) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('218','41','88',1,2) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('219','42','88',49,72) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('220','43','88',24,38) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('221','44','88',6,66) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('222','45','88',31,49) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('223','46','88',9,10) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('224','47','88',57,72) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('225','48','88',17,24) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('226','49','88',41,61) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('227','50','88',33,87) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('228','51','88',11,25) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('229','52','88',1,8) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('230','53','88',14,64) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('231','54','88',50,89) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('232','55','88',16,66) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('233','56','88',0,6) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('234','57','88',18,32) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('235','58','88',6,6) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('236','59','88',68,84) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('237','60','88',50,74) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('238','61','88',7,18) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('239','62','88',14,49) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('240','63','88',3,3) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('241','64','88',21,83) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('242','65','88',48,90) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('243','66','88',11,65) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('244','67','88',29,90) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('245','68','88',44,45) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('246','69','88',23,30) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('247','70','88',53,71) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('248','71','88',50,76) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('249','72','88',13,20) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('250','73','88',6,8) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('251','74','88',7,11) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('252','75','88',0,3) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('253','76','88',49,51) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('254','77','88',37,61) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('255','78','88',4,78) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('257','80','88',23,29) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('256','79','88',1,5) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('259','82','88',1,2) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('258','81','88',3,52) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('260','83','88',65,67) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('261','84','88',41,87) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('262','85','88',20,21) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('93','2','87',43,56) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('94','3','87',27,85) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('263','86','88',46,94) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('264','87','88',64,68) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('265','2','89',5,78) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('266','3','89',29,41) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('267','4','89',2,39) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('268','5','89',57,67) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('269','6','89',1,2) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('270','7','89',68,80) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('271','8','89',22,81) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('272','9','89',9,52) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('273','10','89',26,42) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('274','11','89',42,91) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('275','12','89',23,35) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('276','13','89',38,59) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('277','14','89',43,51) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('278','15','89',19,29) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('279','16','89',21,29) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('280','17','89',18,47) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('281','18','89',26,52) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('282','19','89',18,61) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('283','20','89',33,97) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('284','21','89',1,35) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('285','22','89',41,65) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('286','23','89',16,41) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('287','24','89',26,32) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('288','25','89',0,11) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('289','26','89',30,52) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('290','27','89',29,73) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('291','28','89',26,86) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('292','29','89',48,48) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('293','30','89',0,68) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('294','31','89',25,32) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('295','32','89',37,80) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('296','33','89',12,43) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('297','34','89',34,89) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('298','35','89',54,97) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('299','36','89',2,18) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('300','37','89',13,16) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('301','38','89',19,54) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('302','39','89',16,40) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('303','40','89',10,93) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('304','41','89',35,39) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('305','42','89',24,25) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('306','43','89',5,55) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('307','44','89',9,43) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('308','45','89',36,82) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('309','46','89',5,8) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('310','47','89',18,20) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('311','48','89',2,9) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('312','49','89',34,91) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('313','50','89',27,55) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('314','51','89',11,72) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('315','52','89',8,13) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('316','53','89',4,31) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('317','54','89',1,1) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('318','55','89',7,19) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('319','56','89',3,35) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('320','57','89',58,73) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('321','58','89',2,32) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('322','59','89',51,64) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('323','60','89',34,79) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('324','61','89',44,66) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('325','62','89',37,46) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('326','63','89',10,11) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('327','64','89',15,74) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('328','65','89',8,19) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('329','66','89',13,26) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('330','67','89',0,1) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('331','68','89',5,17) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('332','69','89',0,0) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('333','70','89',1,48) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('334','71','89',13,70) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('335','72','89',24,68) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('336','73','89',21,48) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('337','74','89',17,68) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('338','75','89',72,72) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('339','76','89',6,24) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('340','77','89',18,22) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('341','78','89',8,24) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('342','79','89',26,31) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('343','80','89',14,19) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('344','81','89',10,31) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('345','82','89',88,92) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('346','83','89',5,11) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('347','84','89',13,72) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('348','85','89',18,37) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('349','86','89',6,12) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('350','87','89',79,99) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('351','2','90',10,19) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('353','4','90',8,38) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('352','3','90',3,6) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('354','5','90',26,54) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('355','6','90',20,73) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('356','7','90',30,95) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('357','8','90',32,93) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('358','9','90',4,18) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('359','10','90',32,94) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('360','11','90',57,80) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('361','12','90',3,6) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('362','13','90',40,58) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('363','14','90',54,91) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('364','15','90',10,11) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('365','16','90',34,58) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('366','17','90',34,99) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('367','18','90',72,90) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('368','19','90',13,76) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('369','20','90',37,71) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('370','21','90',21,39) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('371','22','90',4,20) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('372','23','90',11,73) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('373','24','90',18,100) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('375','26','90',0,1) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('374','25','90',26,62) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('376','27','90',10,28) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('377','28','90',68,78) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('378','29','90',10,73) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('379','30','90',73,96) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('380','31','90',35,75) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('381','32','90',58,88) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('382','33','90',14,26) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('383','34','90',22,24) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('384','35','90',23,72) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('385','36','90',23,59) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('387','38','90',51,71) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('386','37','90',3,6) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('388','39','90',48,60) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('389','40','90',44,56) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('390','41','90',25,36) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('391','42','90',32,83) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('392','43','90',77,92) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('393','44','90',30,38) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('394','45','90',43,49) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('395','46','90',23,27) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('396','47','90',78,84) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('397','48','90',26,48) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('398','49','90',15,52) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('399','50','90',4,45) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('400','51','90',53,77) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('401','52','90',5,6) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('402','53','90',17,30) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('403','54','90',4,44) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('404','55','90',12,20) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('405','56','90',15,25) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('406','57','90',1,33) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('407','58','90',22,34) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('408','59','90',6,12) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('409','60','90',3,9) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('410','61','90',41,59) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('411','62','90',16,32) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('412','63','90',7,15) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('413','64','90',49,95) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('414','65','90',41,45) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('416','67','90',11,39) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('415','66','90',18,45) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('417','68','90',26,84) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('418','69','90',3,4) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('419','70','90',72,98) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('420','71','90',26,28) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('421','72','90',2,2) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('422','73','90',57,90) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('423','74','90',12,75) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('424','75','90',23,37) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('425','76','90',22,22) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('426','77','90',30,86) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('427','78','90',44,82) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('428','79','90',13,17) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('429','80','90',38,45) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('430','81','90',26,91) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('431','82','90',34,41) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('432','83','90',19,43) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('433','84','90',43,43) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('434','85','90',34,69) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('435','86','90',10,25) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('436','87','90',18,34) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('437','2','91',25,98) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('438','3','91',15,28) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('439','4','91',56,97) WITH NC;
INSERT INTO <SCHEMA>.INVENTORY (ID,PRODUCT_ID,LOCATION_ID,AVAILABLE,TOTAL) VALUES ('440','5','91',20,30) WITH NC;
-- REM INSERTING into LOCATION
-- SET DEFINE OFF;
INSERT INTO <SCHEMA>.LOCATION (ID,STREET,CITY,ZIPCODE,NAME,GEO) VALUES ('87','7153 East Thomas Road','Scottsdale','85251','Phoenix Equipment Rentals','-111.9271738,33.48034450000001') WITH NC;
INSERT INTO <SCHEMA>.LOCATION (ID,STREET,CITY,ZIPCODE,NAME,GEO) VALUES ('91','2799 Broadway','New York','10025','Cascabel Armory','-73.9676965,40.8029807') WITH NC;
INSERT INTO <SCHEMA>.LOCATION (ID,STREET,CITY,ZIPCODE,NAME,GEO) VALUES ('89','1850 El Camino Real','Menlo Park','94027','Military Weaponry','-122.194253,37.459525') WITH NC;
INSERT INTO <SCHEMA>.LOCATION (ID,STREET,CITY,ZIPCODE,NAME,GEO) VALUES ('92','32/66-70 Marine Parade','Coolangatta','4225','Marine Parade','153.536972,-28.167598') WITH NC;
INSERT INTO <SCHEMA>.LOCATION (ID,STREET,CITY,ZIPCODE,NAME,GEO) VALUES ('90','Tolstraat 200','Amsterdam','1074','Munitions Shopmore','4.907475499999999,52.3530638') WITH NC;
INSERT INTO <SCHEMA>.LOCATION (ID,STREET,CITY,ZIPCODE,NAME,GEO) VALUES ('88','390 Lang Road','Burlingame','94010','Bay Area Firearms','-122.3381437,37.5874391') WITH NC;
-- REM INSERTING into PRODUCT
-- SET DEFINE OFF;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('4','M9',53,75,15,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('3','M1911',53,50,7,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('6','Makarov SD',0,50,8,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('7','PDW',53,75,30,null,'["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('8','Makarov PM',53,50,8,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('9','Double-barreled Shotgun',90,null,2,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('10','Saiga 12K',90,250,8,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('11','Remington 870 (Flashlight)',90,null,8,'Flashlight','Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('12','Revolver',53,100,6,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('13','Winchester 1866',125,150,15,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('14','Bizon PP-19 SD',0,100,64,'Silenced','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('15','MP5SD6',0,100,30,'Silenced','["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('16','MP5A5',53,100,30,null,'["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('17','AK-107',80,400,30,'Kobra sight','["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('18','AK-107 GL',80,null,30,'Kobra sight','["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('19','AK-107 GL PSO',80,400,30,'["Scope","GP-25 launcher"]','["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('20','AK-107 PSO',80,600,30,'Scope','["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('21','AK-74',80,300,30,null,'["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('22','AKM',149,400,30,null,'["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('23','AKS',149,200,30,null,'["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('24','AKS (gold)',149,200,30,null,'["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('25','M1014',90,null,8,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('26','AKS-74 Kobra',80,300,30,'Kobra sight','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('27','AKS-74 PSO',80,400,30,'Scope','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('28','AKS-74U',80,200,30,null,'["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('29','AKS-74UN Kobra',0,300,30,'["Kobra sight","Silenced"]','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('30','AK-74 GP-25',80,300,30,'GP-25 launcher','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('31','FN FAL AN/PVS-4',180,400,20,'NV scope','["Single","Burst"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('32','G36',80,400,30,'["Scope","Aimpoint sight"]','["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('33','FN FAL',180,400,20,null,'["Single","Burst"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('34','G36 C',80,300,30,null,'["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('35','G36-C SD (camo)',0,300,30,'["Aimpoint sight","Silenced"]','["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('36','G36A (camo)',80,400,30,'["Scope","Aimpoint sight"]','["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('37','G36C (camo)',80,300,30,null,'["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('38','G36 K',80,400,30,'["Scope","Aimpoint sight"]','["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('39','G36C-SD',0,300,30,'Aimpoint sight','["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('40','G36K (camo)',80,400,30,'["Scope","Aimpoint sight"]','["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('41','L85A2 ACOG GL',80,600,30,'["ACOG scope","M203 launcher"]','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('42','L85A2 SUSAT',80,300,30,'SUSAT optical scope','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('43','M16A2',80,400,30,null,'["Single","Burst"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('44','L85A2 AWS',80,300,30,'["Thermal scope","NV scope","Laser sight","Variable zoom"]','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('45','L85A2 Holo',80,300,30,'Holographic sight','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('46','Lee Enfield',162,400,10,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('47','M16A4 ACOG',80,600,30,'ACOG scope','["Single","Burst"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('49','M16A2 M203',80,400,30,'M203 launcher','["Single","Burst"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('48','M4A1',80,300,30,null,'["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('50','M4A1 Holo',80,300,30,'["Holographic sight","M203 launcher"]','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('51','M4A1 CCO',80,300,30,'Aimpoint sight','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('52','M4A1 CCO SD',0,200,30,'["Aimpoint sight","Silenced"]','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('53','M4A1 M203 RCO',80,600,30,'["ACOG sight","M203 launcher"]','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('54','M4A3 CCO',80,300,30,'["Aimpoint sight","Flashlight"]','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('55','RPK',80,400,30,null,'["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('56','Sa-58 CCO',149,300,30,'Aimpoint sight','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('57','Sa-58P',149,400,30,null,'["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('58','Sa-58V',149,200,30,null,'["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('59','Sa-58V ACOG',149,400,30,'ACOG sight','["Single","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('60','ER7 RFW',180,2000,25,'["Scope","Aimpoint sight"]','Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('61','AS50',455,1600,5,'Scope','Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('62','KSVK',455,800,5,'Scope','Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('63','CZ550',180,800,5,'Scope','Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('64','DMR',180,800,20,'Scope','Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('65','M107',455,1200,10,'Scope','Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('66','M24',180,800,5,'Scope','Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('67','M40A3',180,800,5,'["Scope","Camo"]','Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('68','M14 AIM',180,500,20,'Aimpoint sight','Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('69','M240',180,400,100,null,'Full auto') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('70','MG36',80,400,100,'Aimpoint sight','["Single","Burst","Full auto"]') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('72','PKM',180,400,100,null,'Full auto') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('71','SVD Camo',180,1200,10,'["Scope","Camo"]','Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('73','Mk 48 Mod 0',180,400,100,'Aimpoint sight','Full auto') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('74','M249 SAW',80,300,200,null,'Full auto') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('75','Crowbar',2,1,null,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('76','Hatchet',2,1,null,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('77','PKP',180,600,100,'Scope','Full auto') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('78','Machete',2,1,null,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('79','M67 Frag Grenade',null,null,null,null,null) WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('80','Compound Crossbow',3,30,1,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('81','Smoke Grenade',null,null,null,null,null) WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('82','M136 Launcher',160,1000,1,null,'Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('83','30Rnd. AK SD',0,null,30,null,null) WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('84','30rnd G36 SD',0,null,30,null,null) WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('85','G36 Mag.',80,null,30,null,null) WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('86','Flashlight',null,null,null,null,null) WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('87','NV Goggles',null,null,null,null,null) WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('2','G17',53,75,15,'Flashlight','Single') WITH NC;
INSERT INTO <SCHEMA>.PRODUCT (ID,NAME,AUDIBLE_RANGE,EFFECTIVE_RANGE,ROUNDS,EXTRAS,FIRE_MODES) VALUES ('5','M9 SD',0,75,15,'Silenced','Single') WITH NC;
-- REM INSERTING into RESERVATION
-- SET DEFINE OFF;
-- REM INSERTING into "SESSION"
-- SET DEFINE OFF;

--------------------------------------------------------
--  View
--------------------------------------------------------

CREATE OR REPLACE VIEW INVENTORY_VIEW
                AS
  SELECT P.name AS product,
    L.name      AS location,
    I.available
  FROM INVENTORY I,
    PRODUCT P,
    LOCATION L
  WHERE p.id = I.product_id
  AND l.id   = I.location_id;

--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CUSTOMER" ADD PRIMARY KEY ("ID");

--------------------------------------------------------
--  Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "INVENTORY" ADD PRIMARY KEY ("ID");

--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "LOCATION" ADD PRIMARY KEY ("ID");

--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "PRODUCT" ADD PRIMARY KEY ("ID");

--------------------------------------------------------
--  Constraints for Table SESSION
--------------------------------------------------------

  ALTER TABLE "SESSION" ADD PRIMARY KEY ("ID");

--------------------------------------------------------
--  Ref Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "INVENTORY" ADD CONSTRAINT "LOCATION_FK" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "LOCATION" ("ID");
  ALTER TABLE "INVENTORY" ADD CONSTRAINT "PRODUCT_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PRODUCT" ("ID");

--------------------------------------------------------
--  Ref Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "RESERVATION" ADD CONSTRAINT "RESERVATION_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER" ("ID");
  ALTER TABLE "RESERVATION" ADD CONSTRAINT "RESERVATION_LOCATION_FK" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "LOCATION" ("ID");
  ALTER TABLE "RESERVATION" ADD CONSTRAINT "RESERVATION_PRODUCT_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PRODUCT" ("ID");

